#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


killall -q polybar
polybar center &
polybar wlan &
polybar left & 
polybar sysmenu &
polybar sound &
polybar keyboard &
polybar battery &
xsetroot -cursor_name left_ptr &

killall dunst
dunst &



bspc config top_padding 40

feh --bg-fill ~/.config/castle.jpg

picom --experimental-backends &

bspc config border_width 0
